# Generated by Django 6.0.3 on 2026-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemstat',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='systemstat',
            name='disk_total_gb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='systemstat',
            name='disk_used_gb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='systemstat',
            name='load_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='systemstat',
            name='memory_total_gb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='systemstat',
            name='memory_used_gb',
            field=models.FloatField(default=0),
        ),
    ]
